### ISSUE TITLE
Monte-Carlo rollout

### ISSUE THREAD

**Issue by WangWenshan** [doubledaibo/gancaption_iccv2017#2]
Hi Dai Bo, 
Thank you for your job. 
I have a question about how to process the variable length of sequences
when you implement the Monte-Carlo rollout algorithm?

`function netTrain.getRolloutReward(rollout_policy, input_x, rollout_num, discriminator)
	local max_seq_length = input_x:size(1)
	local batch_size = input_x:size(2)
	local reward = input_x:clone():zero()
	for i = 1, rollout_num do
		for t = 1, max_seq_length - 1 do
			local dummy, rollout_samples = unpack(rollout_policy:forward({input_x, t}))
			local scores = discriminator:forward(rollout_samples)
			reward[t] = reward[t] + scores	
		end
		local scores = discriminator:forward(input_x)
		reward[max_seq_length] = reward[max_seq_length] + scores
	end 		
	reward = reward:div(rollout_num)
	return reward
end `

Thanks.

**Comment by doubledaibo** [comment]
use a mask
