### ISSUE TITLE
structure issue

### ISSUE THREAD

**Issue by TyrionChou** [doubledaibo/gancaption_iccv2017#9]
hi，bo！
i have question when i read the paper at “With both f(I) and z as the initial conditions, the generator relies on an LSTM net as a decoder, which generates a sentence, word by word. ”
i wonder in what way  sent f(i) and z to lstm? 
The code is written in lua, I am not very familiar with lua, please tell me about it，thank you very much！

**Comment by TyrionChou** [comment]
concating f(i) and z and sent it to lstm as input like words?

**Comment by doubledaibo** [comment]
yes
